---
- block:
  - name: "[MONGODB-APB][MAIN] Deploying MongoDB"
    include_tasks: mongodb.yml
  when: action == 'provision'

- block:
  - name: "[MONGODB-APB][MAIN] Deprovision MongoDB"
    include_tasks: deprovision.yml
  when: action == 'deprovision'

- block:
  - name: "[MONGODB-APB][MAIN] Test MongoDB deployment"
    include_tasks: test.yml
  when: action == 'test'

