---
- name: "[MONGODB-APB][{{ mode }}] Testing MongoDB Deployment"
  debug:
    msg: "{{ mode }} TASKS IN EXECUTION Mode: {{ mode }} State: {{ state }}" 

- name: "[MONGODB-APB][{{ mode }}] Sleeping"
  pause:
    seconds: 10

# Check that MongoDB don't fall down after some seconds
- name: "[MONGODB-APB][{{ mode }}] Ensure that MongoDB is still ready"
  wait_for:
    port: 27017
    host: "{{ mongodb_svc.service.spec.cluster_ip }}"
    timeout: 300
  register: mongodb_conn
  when: state == "present"

- name: "[MONGODB-APB][{{ mode }}] Saving Tests results on error"
  asb_save_test_result:
    fail: True
    msg: "Test Failed. Error connecting with MongoDB. Data - {{ mongodb_conn }}"
  when: mongodb_conn.failed | bool

- name: "[MONGODB-APB][{{ mode }}] Saving Tests results on success"
  asb_save_test_result:
    msg: 'Test Passed! \o/'
  when: not mongodb_conn.failed | bool
