---
- name: "[{{ mode }}][{{ _apb_plan_id }}] Create new project"
  openshift_v1_project:
    name: '{{ namespace }}'

- name: "[{{ mode }}][{{ _apb_plan_id }}] Deploy & Verify MongoDB role"
  include_role:
    name: mongodb-apb
  vars:
    mode: 'test'
    state: 'present'

- name: "[{{ mode }}][{{ _apb_plan_id }}] Deprovision MongoDB role"
  include_role:
    name: mongodb-apb
  vars:
    mode: 'deprovision'
    state: 'absent'

- name: "[{{ mode }}][{{ _apb_plan_id }}] Delete test project"
  openshift_v1_project:
    name: '{{ namespace }}'

